package by.htp3.hotel.controller;

public enum CommandName {
	LOGINATION, REGISTRATION, SHOW_FREE_ROOMS, ADD_NEW_ROOM,
	
	CHANGE_LANGUAGE, ADD_NEW_ROOM_FORM, GO_LOGINATION, GO_REGISTRATION, PERSONAL_ACCOUNT,
	UPDETE_PERSONAL_ACCAUNT
	
}
